intents:
  - StartMessage
  - SetChannel:
      channel: LIST_OF_CHANNELS
  - SetChannelMessage:
      message: SLACK_MESSAGE
      channel: LIST_OF_CHANNELS
  - SetMessage:
      message: SLACK_MESSAGE
  - AMAZON.StartOverIntent
  - AMAZON.HelpIntent
  - AMAZON.YesIntent
  - AMAZON.NoIntent
  - AMAZON.StopIntent
  - AMAZON.CancelIntent

slots:
  LIST_OF_CHANNELS:
    - random
    - general
    - botstuff
    - foos
  SLACK_MESSAGE:
    - Hello
    - Hello World
    - This is my message
    - Hey
    - I'm on my way
    - I'm running late today
    - This is a short message
    - This is a longer message with more words that I want people in slack to see
    - OK
    - of course
    - of course not
    - that's fine
    - that's right
    - sure
    - certainly
    - definitely
    - absolutely
    - as soon as possible
    - that's enough
    - it doesn't matter
    - it's not important
    - it's not serious
    - it's not worth it
    - I'm in a hurry
    - I've got to go
    - I'm going out
    - sleep well
    - same to you
    - me too
    - not bad
    - I like him
    - I like her
    - I like it
    - I don't like him
    - I don't like her
    - I don't like it
    - thanks for your help
    - thanks for your email
    - thanks for everything
    - I'm sorry
    - I'm really sorry
    - sorry I'm late
    - sorry to keep you waiting
    - sorry for the delay
    - great
    - come on
    - only joking
    - just kidding
    - that's funny
    - that's life
    - damn it
    - dammit
    - let's go
    - hurry up
    - get a move on
    - calm down
    - steady on
    - hang on a second
    - hang on a minute
    - one moment, please
    - just a minute
    - take your time
    - please be quiet
    - shut up
    - stop it
    - don't worry
    - don't forget
    - help yourself
    - go ahead
    - let me know
    - where are you
    - what's this
    - what's that
    - is anything wrong
    - what's the matter
    - is everything OK
    - have you got a minute
    - really
    - are you sure
    - what's going on
    - what's happening
    - what happened
    - how many
    - how much
    - well done
    - good luck
    - bad luck
    - never mind
    - what a pity
    - what a shame
    - happy birthday
    - happy New Year
    - happy Easter
    - happy Christmas
    - merry Christmas
    - happy Valentine's Day
    - glad to hear it
    - sorry to hear that
    - I'm tired
    - I'm happy
    - I'm exhausted
    - I'm hungry
    - I'm thirsty
    - I'm bored
    - I'm worried
    - I'm looking forward to it
    - I'm in a good mood
    - I'm in a bad mood
    - I can't be bothered
    - see you tomorrow
    - I agree
    - I disagree
    - I don't agree
    - that's true
    - that's not true
    - I think so
    - I don't think so
    - I hope so
    - I hope not
    - you're right
    - you're wrong
    - I don't mind
    - it's up to you
    - that depends
    - that's interesting
    - ha ha ha
    - haha


utterances:
  StartMessage:
    - I want to post a message
    - Start a message
    - Write message
    - Send message
    - Post message
  SetChannel:
    - '{channel}'
    - I want to post to {channel}
    - I'd like to post to {channel}
    - post to {channel}
    - send to {channel}
    - message {channel}
  SetChannelMessage:
    - I want to post {message} to {channel}
    - I want to post {message} in {channel}
    - I want to send {message} to {channel}
    - I want to send {message} in {channel}
    - I want to write {message} to {channel}
    - I want to write {message} in {channel}
    - I want to message {message} to {channel}
    - I want to message {message} in {channel}
    - I'd like to post {message} to {channel}
    - I'd like to post {message} in {channel}
    - I'd like to send {message} to {channel}
    - I'd like to send {message} in {channel}
    - I'd like to write {message} to {channel}
    - I'd like to write {message} in {channel}
    - I'd like to message {message} to {channel}
    - I'd like to message {message} in {channel}
    - post {message} in {channel}
    - post {message} to {channel}
    - send {message} in {channel}
    - send {message} to {channel}
    - message {message} in {channel}
    - message {message} to {channel}
    - write {message} in {channel}
    - write {message} to {channel}
  SetMessage:
    - '{message}'
    - I want to post {message}
    - I want to send {message}
    - I want to message {message}
    - I want to write {message}
    - post {message}
    - send {message}
    - write {message}
    - message {message}